#!/bin/bash
export SDKMAN_DIR="$HOME/.sdkman"
if [[ -s "$SDKMAN_DIR/bin/sdkman-init.sh" ]]; then
    source "$SDKMAN_DIR/bin/sdkman-init.sh" > /dev/null 2>&1
    sdk "$@"
else
    echo "SDKMAN! not found" >&2
    exit 1
fi