package misc

// 沙盒类工具补充提示词
func AttackSandboxPrompt() string {
	return `1. This tool runs in a sandbox environment. All operations that involve connecting to other container services must specify the complete IP address, not 127.0.0.1.
2. All tools running in the sandbox share the same file system, so you can use files generated by previously executed commands.`
}
