// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAPIBaseURL() {
  return window['go']['main']['App']['GetAPIBaseURL']();
}

export function GetBasicAuthPassword() {
  return window['go']['main']['App']['GetBasicAuthPassword']();
}

export function GetBasicAuthUser() {
  return window['go']['main']['App']['GetBasicAuthUser']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
